spring:
  application:
    name: play-integrity-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gcp:
      credentials:
        location: ${PLAY_INTEGRITY_API_CREDENTIALS_JSON:classpath:play-integrity-credentials.json}

server:
  port: 8080

# https://developer.android.com/google/play/integrity/overview
play-integrity-api:
  credentials-file: ${PLAY_INTEGRITY_API_CREDENTIALS_JSON:play-integrity-credentials.json}
  application-name: project_id # project_id in play-integrity-credentials.json file
